"""add link_url to achievement

Revision ID: 772d117733e2
Revises: 62d7e83f01b1
Create Date: 2026-04-30 20:03:58.902878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772d117733e2'
down_revision = '62d7e83f01b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_column('link_url')

    # ### end Alembic commands ###
