"""Initial schema

Revision ID: 62d7e83f01b1
Revises: 
Create Date: 2026-04-30 19:42:29.136134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d7e83f01b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('architecture', sa.Text(), nullable=True),
    sa.Column('failure_handling', sa.Text(), nullable=True),
    sa.Column('tradeoffs', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('live_url', sa.String(length=255), nullable=True),
    sa.Column('chat_url', sa.String(length=255), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('reading_time', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_sections')
    op.drop_table('skills')
    op.drop_table('projects')
    op.drop_table('achievements')
    # ### end Alembic commands ###
